- name: Push the file on the Target node
  copy:
    src: "{{ Intermidiatory_Files }}/deployDockerImage/K8S/Docker/scratch.py"
    dest: "/Users/somye/Library/Preferences/PyCharmCE2019.1/scratches"
    remote_src: no
    owner: somye
    group: somye

- name: Deploy docker image and rollout on kubernetes
  shell: |
    docker build -t sampleapp:latest /Users/somye/Library/Preferences/PyCharmCE2019.1/scratches
    kubectl rollout restart deployment/hello-python 
