pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
            git branch: 'main',  url: 'https://github.com/somye91/K8S.git'
            }
        }
        stage('Deploy') {
            steps {
                
                sh '''
                    cp /my/dir/scratch.py /Users/somye/Library/Preferences/PyCharmCE2019.1/scratches/scratch.py
                    docker build -t sampleapp:latest /Users/somye/Library/Preferences/PyCharmCE2019.1/scratches
                    kubectl rollout restart deployment/hello-python 
                '''
            }
        }
    }
}
