pipeline {
    agent any
    stages {
        
        stage('Deploy') {
            steps {
                
                sh '''
                    cp /my/dir/scratch_v1.py /Users/somye/Library/Preferences/PyCharmCE2019.1/scratches/scratch.py
                    docker build -t sampleapp:latest /Users/somye/Library/Preferences/PyCharmCE2019.1/scratches
                    kubectl rollout restart deployment/hello-python 
                '''
            }
        }
    }
}
